// inertia/components/ui/command/CommandShortcut.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <span
    data-slot="command-shortcut"
    :class="
      cn(
        'text-muted-foreground group-data-highlighted/command-item:text-foreground ml-auto text-xs tracking-widest',
        props.class
      )
    "
  >
    <slot />
  </span>
</template>

// client/src/lib/components/ui/command/command-shortcut.svelte
<script lang="ts">
	import { cn, type WithElementRef } from '@/utils';
	import type { HTMLAttributes } from 'svelte/elements';

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLSpanElement>> = $props();
</script>

<span
	bind:this={ref}
	data-slot="command-shortcut"
	class={cn('text-muted-foreground ml-auto text-xs tracking-widest', className)}
	{...restProps}
>
	{@render children?.()}
</span>
